### ISSUE TITLE
magick with rmarkdown

### ISSUE THREAD

**Issue by oganm** [ropensci/magick#108]
I have been trying to use Rmarkdown with magick expecting it would work similar to plots or not work at all but instead I get links to non-existent images in `/tmp` in the output. I tried looking at the readme.rmd here to see how you did it and it seems none of the code in the rmd file is actually evaluated. Is the supported way to use it with markdown is to link to saved images or is this a temporary state of affairs?

**Comment by jeroen** [comment]
What r markdown renderer do you use? Everything works fine with knitr, for example the magick vignette is also rmd. Do you mean the rstudio notebook perhaps?

**Comment by oganm** [comment]
I am using Rstudio but it is a regular rmd file not a notebook. My minimal RMD file:

    ---
    output: github_document
    ---

    ```{r, message=FALSE}
    library(magick)

    frink <- image_read("https://jeroen.github.io/images/frink.png")
    frink
    ```

It's output when using rstudio's knit button

    ``` r
    library(magick)

    frink <- image_read("https://jeroen.github.io/images/frink.png")
    frink
    ```

    <img src="/tmp/RtmpkKcaxT/file585f4222947.png" width="220" />

It's output when using `knitr::knit`

    ---
    output: github_document
    ---


    ```r
    library(magick)
    
    frink <- image_read("https://jeroen.github.io/images/frink.png")
    frink
    ```

    ![plot of chunk unnamed-chunk-1](/tmp/RtmpyzrgUX/file5ab3e41af79.png)

**Comment by jeroen** [comment]
Try removing the `output: github_document`

**Comment by oganm** [comment]
No change in either of them

**Comment by jeroen** [comment]
The tmp images are actually expected but pandoc should turn those into embedded images before deleting them. Did you change anything in your pandoc settings?

**Comment by jeroen** [comment]
Make sure to select "knit to html" in rstudio...

**Comment by gadenbuie** [comment]
It would be really great if magick could write into `<Rmd_doc_name>_files/figure-gfm/` (or similar) when using `output: github_document` (or other formats, actually).

For example in a `Readme.Rmd` this code chunk

````
```{r plot-demo}
ggplot2::qplot(factor(cyl), data = mtcars, fill = factor(gear))

# Produce graphic
fig <- image_graph(width = 800, height = 600, res = 96)
ggplot2::qplot(factor(cyl), data = mtcars, fill = factor(gear))
invisible(dev.off())

print(fig)
```
````

would output

```
...qplot code subchunk...
![](Readme_files/figure-gfm/plot-demo-1.png)<!-- -->

...magick code subchunk...
![](Readme_files/figure-gfm/plot-demo-2.png)<!-- -->
```

Or even having it just output following current naming practice would be great.

```
![](Readme_files/figure-gfm/file133dc4548023.png)<!-- -->
```

Btw, it doesn't work because it currently outputs something like this

```
![](/var/folders/qy/gyl9x1w92m5brmly42cp1vmw0000gn/T//Rtmpy6QgN6/file133dc4548023.png)<!-- -->
```

Anyway, I'd be happy to take a stab at a PR for this if you could point me to where I should go looking around in the codebase.

**Comment by jeroen** [comment]
Thank you for these suggestions. I committed a variation of the PR by @gadenbuie. Would you have a chance to test this?

**Comment by oganm** [comment]
Can confirm it works for me
