### ISSUE TITLE
Support raster conversion

### ISSUE THREAD

**Issue by jeroenooms** [ropensci/magick#13]
I think we need to implement S4 methods for:

```
raster	To create a RasterLayer
stack	To create a RasterStack (multiple layers)
brick	To create a RasterBrick (multiple layers)
```

**Comment by mdsumner** [comment]
There's a lot more to say here but this is simple pathway for frink: 

```{r}
## I can't see how to get values from magick?
a <- png::readPNG("frink.png")

## scale up to integer
rr <- raster::brick(a) * 256

raster::plotRGB(rr, asp = 1)
```

A raster object can also store a colortable() as an internal lookup for a single RasterLayer - you get this automatically from `raster("file.gif")`. 

Trivially, you could get the filename of the magick source and pass that to `raster()` or `brick()` - but often that will dispatch to rgdal to do the work. 

There's a lot more to say!  Happy to help with driving raster, but will need some guidelines on how much to do. I see a lot of promise for demand-paging, using raster tools to control the geographic context, and making nice maps with other layers.

**Comment by mdsumner** [comment]
Does ImageMagick have any concept of an affine transform for a "world" coordinate system outside of the grid index? Does cropping preserve the original [0, nx] / [0, ny] extent?

**Comment by jeroenooms** [comment]
@mdsumner IM allows for exporting in almost any format, I just need to know what `raster` needs. Currently you can extract a frame as a raw buffer using `[[`. For example:

```r
frink <- image_read("https://jeroenooms.github.io/images/frink.png")
buf <- frink[[1]]
dim(buf)
```

**Comment by mdsumner** [comment]
@jeroenooms cool - that's pretty much it for in-memory objects then. If it's a 2D matrix i.e. greyscale then either `raster::raster()` or `raster::brick()` will accept that too, and if it's a palette then that can be set with `colortable()`.  

You can see the palette case with this, but I can't see how to get that palette via magick: 

```R
image_write(fr, "frick.gif", format = "gif")
rgif <- raster("frick.gif")
plot(rgif)  ## single layer, index into colortable(rgif)
```

If there is no "affine transform" I highly recommend that the default extent be set to  [0, ncol, 0, nrow] rather than the default [0, 1, 0, ] with `setExtent` or the `xmn/xmx/ymn/ymx` args to raster/brick. This way raster::crop will preserve the original "global" extent in a natural way, but it's easy to modify anyway. 

`raster` does support a shear transform but it's pretty rare, it's set internally in  `@rotation@geotrans`. I'll get some examples together.

**Comment by jeroenooms** [comment]
I have no idea what affine transform is, but it seems imagemagick supports it: http://www.imagemagick.org/Usage/distorts/affine/

**Comment by mdsumner** [comment]
Affine transform is the scaling and offset (and shear - but this is rare) applied to an image to place it into a "world" coordinate system, a special case of a linear transform: 

https://en.wikipedia.org/wiki/Affine_transformation

It's best known by the primitive "world file" that accompanies raw formats that don't have internal metadata: https://en.wikipedia.org/wiki/World_file

In raster, it the scaling and offset is usually applied and interrogated via the "Extent" class, which is just the "world coordinates" xmin, xmax, ymin, ymax of the lower left, and upper right corner edges of the image. A Raster object may have a "geotrans" slot for the more general affine, but this is rarely used afaics and may not be implemented fully. 

I wonder if it's worth using the IM affine to capture that information from a raster source?  The analogy for non-geospatial imagery would be that any sub-image records its position within a default  space (say [0,1,0,1]) that the parent occupied.

**Comment by jeroenooms** [comment]
Thanks for your input. Merging this discussion with https://github.com/ropensci/magick/issues/7.
