### ISSUE TITLE
binary builds of magick can't find dithering files

### ISSUE THREAD

**Issue by thomasp85** [ropensci/magick#304]
The files defining the ordered dithering in ImageMagick is located in `/etc/ImageMagick/thresholds.xml`. When installing magick as a binary build these are not found an the `image_ordered_dither()` won't work

Bundling the thresholds.xml file and making it discoverable with the correct `MAGICK_CONFIGURE_PATH` is a possible way forward. I don't think there's anyway around bundling it though

**Comment by jeroen** [comment]
@dlemstra question from me again :) 

On some platforms we build imagemagick `--with-zero-configuration` as a static library. Is it expected that we won't be able to use ordered_dither because `thresholds.xml` is not there? I thought `--with-zero-configuration` would maybe hardcode these configs into the binary.

**Comment by jeroen** [comment]
Upstream issue here --> https://github.com/ImageMagick/ImageMagick6/issues/137

**Comment by jeroen** [comment]
This should be fixed in magick 2.7.1
