### ISSUE TITLE
example (challenge?): convert all pixels of color A to color B

### ISSUE THREAD

**Issue by jennybc** [ropensci/magick#32]
I just captured some hand-drawings with a black "pen" then realized I needed to use them on a dark background. So I wanted to switch every pixel that is, say, "#FFFFFF" to "#000000".

I used the command line. This, cribbed from [here](http://www.imagemagick.org/discourse-server/viewtopic.php?t=17897), worked on the first try 😮:

```
mogrify -path ./ -format pdf -fill "#FFFFFF" -opaque "#000000" *.pdf
```

I didn't try it with magick yet, but it would be interesting to see if this is easy. If not, could it be? If it is, it might make a useful example.

Representative input file.
[Arrows-jenny-2016-11-06.pdf](https://github.com/ropensci/magick/files/574334/Arrows-jenny-2016-11-06.pdf)

**Comment by dmypstl** [comment]
I can think of several ways to achieve it. 
``` r
library(magick)
fig <- image_read_pdf("pdfs/Arrows-jenny-2016-11-06.pdf") 
```
In a simplest case of grayscale drawing, inverting the colors may sometime make sense:
``` r
fig %>% 
  image_negate()
```
You could also consider recoloring the background without touching the main drawing:
```r
fig %>% 
  image_transparent("white", fuzz=50) %>% 
  image_background("teal")
```

Finally, you may want to pick out one particular color from the picture (here reached by `1x1` image properties)
```r
col <- fig %>% image_crop("1x1+2150+1450") %>% image_raster() %>% .[["col"]]

fig %>% image_transparent(color = col, fuzz = 70) %>% 
  image_background("pink")
```
The last one is pretty remarkable because after `image_transparent` new channels get created, so you can do really cool stuff like use shapes as masks:

```r
mask <- fig %>%
  image_fill("red", point="+2150+1450", fuzz=50) %>% 
  image_transparent("red", fuzz=50) %>%
  image_channel("Opacity") %>% 
  image_median(radius = 5) %>% image_trim()

cool_gradient <- image_blank(image_info(mask)$width, image_info(mask)$height, 
                            pseudo_image = "radial-gradient:purple-yellow")

image_composite(cool_gradient, mask, operator = "CopyOpacity")
```
![masked](https://user-images.githubusercontent.com/36849506/40630879-e17918f0-62d6-11e8-9dac-af160dc48624.png)

**Comment by jeroen** [comment]
If your input image does not have transparency, an easy method is setting the pixels to transparent and then colorizing them via a background color like so:


```r
image_transparent(logo, 'blue', fuzz = 50) %>%
   image_background('pink')
```
